version: '2'
services:
  app:
    # restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ${IMAGE_NAME}
    ports:
      - ${PORT}:80
    volumes:
      - ${SRC}:/var/www/html
    depends_on:
      - "db"
  db:
    restart: always
    image: postgres
    ports:
      - ${DBPORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ${DBDATA}:/var/lib/postgresql/data
